### ISSUE TITLE
Max samples per analysis

### ISSUE THREAD

**Issue by teresaperinan** [pughlab/VisCap#11]
I am involved in a project of targeted sequencing where I want to analyze 384 samples for CNV. How many samples can I analyze per run? Could I run all the samples in just one analysis? Thank you

**Comment by tjpugh** [comment]
The limited will be available memory and desired processing time. If these aren’t limited, then yes, you could run all samples at once. It may be more efficient to run the samples in the batches in which they were sequenced so that you correct for any batch effects.

_____________________________
