### ISSUE TITLE
Missing gene annotation in the output files

### ISSUE THREAD

**Issue by rframal** [pughlab/VisCap#9]
Hi,

I am testing the VisCap. It is working well but I can not get the gene name in the file "cnv_boxplot_outliers.xls".

My interval file looks like the following:

@hd	VN:1.5 SO:coordinate
@sq	SN:chrM LN:16569 M5:c68f52674c9fb33aef52dcf399755519 UR:file:/data1/ref/Homo_sapiens.GRCh37.75.genome.fa
@sq	SN:chr1 LN:249250621 M5:1b22b98cdeb4a9304cb5d48026a85128 UR:file:/data1/ref/Homo_sapiens.GRCh37.75.genome.fa
@sq	SN:chr2 LN:243199373 M5:a0d9851da00400dec1098a9255ac712e UR:file:/data1/ref/Homo_sapiens.GRCh37.75.genome.fa
@sq	SN:chr3 LN:198022430 M5:641e4338fa8d52a5b781bd2a2c08d3c3 UR:file:/data1/ref/Homo_sapiens.GRCh37.75.genome.fa
@sq	SN:chr4 LN:191154276 M5:23dccd106897542ad87d2765d28a19a1 UR:file:/data1/ref/Homo_sapiens.GRCh37.75.genome.fa
@sq	SN:chr5 LN:180915260 M5:0740173db9ffd264d728f32784845cd7 UR:file:/data1/ref/Homo_sapiens.GRCh37.75.genome.fa
@sq	SN:chr6 LN:171115067 M5:1d3a93a248d92a729ee764823acbbc6b UR:file:/data1/ref/Homo_sapiens.GRCh37.75.genome.fa
@sq	SN:chr7 LN:159138663 M5:618366e953d6aaad97dbe4777c29375e UR:file:/data1/ref/Homo_sapiens.GRCh37.75.genome.fa
@sq	SN:chr8 LN:146364022 M5:96f514a9929e410c6651697bded59aec UR:file:/data1/ref/Homo_sapiens.GRCh37.75.genome.fa
@sq	SN:chr9 LN:141213431 M5:3e273117f15e0a400f01055d9f393768 UR:file:/data1/ref/Homo_sapiens.GRCh37.75.genome.fa
@sq	SN:chr10 LN:135534747 M5:988c28e000e84c26d552359af1ea2e1d UR:file:/data1/ref/Homo_sapiens.GRCh37.75.genome.fa
@sq	SN:chr11 LN:135006516 M5:98c59049a2df285c76ffb1c6db8f8b96 UR:file:/data1/ref/Homo_sapiens.GRCh37.75.genome.fa
@sq	SN:chr12 LN:133851895 M5:51851ac0e1a115847ad36449b0015864 UR:file:/data1/ref/Homo_sapiens.GRCh37.75.genome.fa
@sq	SN:chr13 LN:115169878 M5:283f8d7892baa81b510a015719ca7b0b UR:file:/data1/ref/Homo_sapiens.GRCh37.75.genome.fa
@sq	SN:chr14 LN:107349540 M5:98f3cae32b2a2e9524bc19813927542e UR:file:/data1/ref/Homo_sapiens.GRCh37.75.genome.fa
@sq	SN:chr15 LN:102531392 M5:e5645a794a8238215b2cd77acb95a078 UR:file:/data1/ref/Homo_sapiens.GRCh37.75.genome.fa
@sq	SN:chr16 LN:90354753 M5:fc9b1a7b42b97a864f56b348b06095e6 UR:file:/data1/ref/Homo_sapiens.GRCh37.75.genome.fa
@sq	SN:chr17 LN:81195210 M5:351f64d4f4f9ddd45b35336ad97aa6de UR:file:/data1/ref/Homo_sapiens.GRCh37.75.genome.fa
@sq	SN:chr18 LN:78077248 M5:b15d4b2d29dde9d3e4f93d1d0f2cbc9c UR:file:/data1/ref/Homo_sapiens.GRCh37.75.genome.fa
@sq	SN:chr19 LN:59128983 M5:1aacd71f30db8e561810913e0b72636d UR:file:/data1/ref/Homo_sapiens.GRCh37.75.genome.fa
@sq	SN:chr20 LN:63025520 M5:0dec9660ec1efaaf33281c0d5ea2560f UR:file:/data1/ref/Homo_sapiens.GRCh37.75.genome.fa
@sq	SN:chr21 LN:48129895 M5:2979a6085bfe28e3ad6f552f361ed74d UR:file:/data1/ref/Homo_sapiens.GRCh37.75.genome.fa
@sq	SN:chr22 LN:51304566 M5:a718acaa6135fdca8357d5bfe94211dd UR:file:/data1/ref/Homo_sapiens.GRCh37.75.genome.fa
@sq	SN:chrX LN:155270560 M5:7e0e2e580297b7764e31dbc80c2540dd UR:file:/data1/ref/Homo_sapiens.GRCh37.75.genome.fa
@sq	SN:chrY LN:59373566 M5:1fa3474750af0948bdf97d5a0ee52e51 UR:file:/data1/ref/Homo_sapiens.GRCh37.75.genome.fa
chr1 10292320 10292502 + KIF1B
chr1 10316296 10316391 + KIF1B
chr1 10318542 10318740 + KIF1B

Is this the correct interval file format ? Could you please show me an example of the corrected interval file ?

Best,

Rodrigo

**Comment by arnavaz** [comment]
Hi Rodrigo,
first you do not need the header lines in you bed file. You only need the chrom number, start and end columns and gene name column. Also make sure that these columns are tab separated. 
Let me know if this helps.
Arna

**Comment by rframal** [comment]
Hi Arna,

Thanks for your answer.

Actually my first try was with a bed file as you described: With chr,
start, end and gene symbol, all tab separated and without any header.
Altough the program run normally,  the gene/exon name column was also empty  in
the output files.

Any other suggestions?

Best,


Em qua, 25 de abr de 2018 17:08, arnavaz <notifications@github.com>
escreveu:

**Comment by tjpugh** [comment]
Can you try naming your intervals using the convention GENE_EXON_01, GENE_EXON_02, etc? There is a split on _ to parse out gene and exon names.

- Trevor

**Comment by arnavaz** [comment]
Hi Rodrigo,
Could you please send you bed file to me? 
Also, when  you ran DepthofCoverage tool, did you use the exact same bed file? You have to use the exact same bed file for both DofCov and VisCap.

Arna

**Comment by rframal** [comment]
Hi Arna,

Yes, I am using the same bed file in VisCap and DepthofCoverage tools.

Actually I try two distinct formats of bed files

chr1    10292319    10292559    KIF1B
chr1    10316237    10316447    KIF1B
chr1    10318490    10318790    KIF1B
chr1    10321905    10322085    KIF1B
chr1    10327376    10327676    KIF1B

and

chr1    17345217    17345246    ENSG00000117118:001
chr1    17345247    17345453    ENSG00000117118:002
chr1    17349103    17349225    ENSG00000117118:003
chr1    17349226    17349531    ENSG00000117118:004

All tab-delimited and without any headers. Both failed to create an
annotated result file.

Could you please show me an example bed that you know that works ?

Best,





Em qui, 26 de abr de 2018 11:55, arnavaz <notifications@github.com>
escreveu:

**Comment by arnavaz** [comment]
Hi Rodrigo,

Here is an example of a bed file,  I am printing here only a few lines of it:


1	15818729	15819569	CASP9_NM_001229	
1	15820321	15820561	CASP9_NM_001229	
1	15821737	15821977	CASP9_NM_001229	
1	15831059	15831299	CASP9_NM_001229	
1	15832439	15832619	CASP9_NM_001229	
1	15833361	15833601	CASP9_NM_001229	
1	15834294	15834474	CASP9_NM_001229	
1	15844567	15844927	CASP9_NM_001229	
1	15850526	15850766	CASP9_NM_001229	
1	15850820	15850940	CASP9_NM_001229

**Comment by arnavaz** [comment]
The above file is tab separated. The header is not required and the four columns here are mandatory.

**Comment by rframal** [comment]
I found the solution adding 1 to the start position of bed file" . To fix
it, I just changed the following line of the "load_interval_names" function
from VisCap.R code.

From:
rownames(tab) <- paste(tab$chr, ":", tab$start, "-", tab$end, sep = "") #
Original line

To:
rownames(tab) <- paste(tab$chr, ":", tab$start+1, "-", tab$end, sep = "") #
Add 1 to start positions from bed file

This happened because GATK DepthofCoverage adds 1 to the start position of
bed.

Best,



2018-05-01 16:45 GMT-03:00 arnavaz <notifications@github.com>:

**Comment by arnavaz** [comment]
That is weird. Which version on DofCov are you running? We never had to do this...

**Comment by rframal** [comment]
We are using the version 3.7.0 of GATK


Em qua, 2 de mai de 2018 12:02, arnavaz <notifications@github.com> escreveu:
